### ISSUE TITLE
error instalation

### ISSUE THREAD

**Issue by xor256** [neutralinojs/neutralinojs#1034]
```
neu create myapp
/usr/local/lib/node_modules/@neutralinojs/neu/src/utils.js:42
    return path?.replace(/^\//, '');
                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@neutralinojs/neu/src/modules/downloader.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@neutralinojs/neu/src/modules/creator.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

```

**Comment by hv6erT** [comment]
Which version of node js do you have?

**Comment by shalithasuranga** [comment]
Hey @hv6erT, yeah seems like a Node.js version issue. @xor256 Please check: https://github.com/neutralinojs/neutralinojs-cli#requirements
