### ISSUE TITLE
Update from 4.11 to 4.12 crash

### ISSUE THREAD

**Issue by globules-io** [neutralinojs/neutralinojs#1119]
Windows 10 x64
Node 18

1. Update from 4.11 to 4.12 in config file
2. type neu update

```
neu: INFO Downloading Neutralinojs binaries..
neu: INFO Extracting zip file..
neu: INFO Finalizing and cleaning temp. files.
node:fs:1596
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, stat '.tmp/WebView2Loader.dll'
    at Object.statSync (node:fs:1596:3)
    at Object.statSync (C:\Users\Eric\AppData\Roaming\npm\node_modules\@neutralinojs\neu\node_modules\graceful-fs\polyfills.js:318:34)
    at statSync (C:\Users\Eric\AppData\Roaming\npm\node_modules\@neutralinojs\neu\node_modules\fs-extra\lib\util\stat.js:10:52)
    at getStatsSync (C:\Users\Eric\AppData\Roaming\npm\node_modules\@neutralinojs\neu\node_modules\fs-extra\lib\util\stat.js:24:19)
    at Object.checkPathsSync (C:\Users\Eric\AppData\Roaming\npm\node_modules\@neutralinojs\neu\node_modules\fs-extra\lib\util\stat.js:49:33)
    at Object.copySync (C:\Users\Eric\AppData\Roaming\npm\node_modules\@neutralinojs\neu\node_modules\fs-extra\lib\copy-sync\copy-sync.js:24:38)
    at module.exports.downloadAndUpdateBinaries (C:\Users\Eric\AppData\Roaming\npm\node_modules\@neutralinojs\neu\src\modules\downloader.js:108:13)
    at async Command.<anonymous> (C:\Users\Eric\AppData\Roaming\npm\node_modules\@neutralinojs\neu\src\commands\update.js:10:13) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: '.tmp/WebView2Loader.dll'
```

**Comment by shalithasuranga** [comment]
Hey.. Thanks for reporting this. Could you please use the latest CLI? :tada:

**Comment by globules-io** [comment]
Worked after updating the CLI. Maybe the update comment should verify local CLI version first ? Anyway, it works now.

**Comment by shalithasuranga** [comment]
@globules-io Thanks for checking. hmm, yeah it's better to use backward compatibility there and have a check. But, I think app developers can always use the latest version. We'll add a notice about newer CLI released via https://github.com/neutralinojs/neutralinojs-cli/issues/210

Thanks for your suggestion :tada:
