### ISSUE TITLE
Compatibility with SvelteKit

### ISSUE THREAD

**Issue by jerrygreen** [neutralinojs/neutralinojs#1200]
**Is your feature request related to a problem? Please describe.**
Is there compatibility with SvelteKit? I found these instructions on Stackoverflow but it seems outdated:

- [Is there a way to create a NeutralinoJS project based on Svelte and Typescript?](https://stackoverflow.com/questions/71705998/is-there-a-way-to-create-a-neutralinojs-project-based-on-svelte-and-typescript)

Instructions look cool except they don't work: they seem to be for Svelte not SvelteKit.

**Describe the solution you'd like**
I'd like to have some info in docs how to run Neutralino with the SvelteKit sample app.

**Describe alternatives you've considered**
I tried to figure out how to merge both of them, but it's seems untrivial since I'm new with Neutralino. I happen to make SvelteKit work with Electron but this ain't helping to figure out Neutralino.

**Comment by OrigamingWasTaken** [comment]
I'm seeing this is still open. For now I made a template for Svelte, and if you want to use SvelteKit, you can tweak it a bit: https://github.com/OrigamingWasTaken/neutralino-svelte

**Comment by nzoschke** [comment]
I'm also trying to get SvelteKit working following the "Using Frontend Libraries" doc.

I have this command:

```json
{
  "cli": {
    "frontendLibrary": {
      "patchFile": "/src/app.html",
      "devUrl": "http://localhost:5173/",
      "devCommand": "npm run dev",
      "initCommand": "npm install",
      "buildCommand": "npm run build",
      "projectPath": "/"
    }
}
```

And `src/app.html` that SvelteKit created, plus the `__neutralino_globals` script:

```html
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" href="%sveltekit.assets%/favicon.png" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		%sveltekit.head%
		<script src="%PUBLIC_URL%/__neutralino_globals.js"></script>
	</head>
	<body data-sveltekit-preload-data="hover">
		<div style="display: contents">%sveltekit.body%</div>
	</body>
</html>
```

However the HMR patch doesn't work. `neu` keeps repeating `Global variables patch was reverted.` on the console. And SvelteKit and/or Vite doesn't like that <script> tag and returns a `decodeURI` error.

```bash
$ neu run
neu: INFO Running devCommand: npm run dev...
neu: INFO Global variables patch was reverted.

> webview@0.0.1 dev
> vite dev


  VITE v5.4.10  ready in 402 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
neu: INFO Starting process: neutralino-mac_arm64  --load-dir-res --path=. --export-auth-info --neu-dev-extension  --url=http://localhost:5173/
INFO 2024-10-25 09:55:31,981 Auth info was exported to ./.tmp/auth_info.json api/debug/debug.cpp:17 noah@unknown-host
neu: INFO Global variables patch was reverted.
9:55:32 AM [vite] Internal server error: URI malformed
      at decodeURI (<anonymous>)
      at file:///Users/noah/src/webview/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:403:19
      at call (file:///Users/noah/src/webview/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:41363:7)
      at next (file:///Users/noah/src/webview/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:41307:5)
      at Function.handle (file:///Users/noah/src/webview/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:41310:3)
      at Server.app (file:///Users/noah/src/webview/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:41175:37)
      at Server.emit (node:events:519:28)
      at parserOnIncoming (node:_http_server:1150:12)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:118:17)
neu: INFO Global variables patch was reverted.
neu: INFO Global variables patch was reverted.

```

<img width="912" alt="Screenshot 2024-10-25 at 9 54 54 AM" src="https://github.com/user-attachments/assets/a8fa6f9b-afb6-4fef-9633-1ab94c1e86d3">


However if I specify a fixed port in `neutralino.config.json` and use that in `src/app.html` everything is fine with HMR.

```json
{
  "port": 5006,
}
```

```html
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" href="%sveltekit.assets%/favicon.png" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		%sveltekit.head%
		<script src="http://localhost:5006/__neutralino_globals.js"></script>
	</head>
	<body data-sveltekit-preload-data="hover">
		<div style="display: contents">%sveltekit.body%</div>
	</body>
</html>
```

**Comment by CosmoMyzrailGorynych** [comment]
Here is my template for those seeking with Svelte + TypeScript + Vite: https://github.com/CosmoMyzrailGorynych/neutralino-svelte-typescript-template
