### ISSUE TITLE
Unable to create the application.

### ISSUE THREAD

**Issue by WannaCry016** [neutralinojs/neutralinojs#1336]
**Describe the bug**
When trying to create a new Neutralinojs app using the neu create command, the process fails with an Error: read ECONNRESET. This error appears during the step where the CLI downloads the Neutralinojs binaries. The issue prevents the app creation from completing successfully.

**To Reproduce**

- Open a terminal.
- Run the command neu create tyo.
- Wait for the process to progress through the template download and extraction steps.
- Observe the error during the binary download phase.
- Expected behavior
- The app creation process should complete without errors. A new Neutralinojs app should be created in the specified directory, including all required binaries.

**Screenshots/Screen recordings**
![Screenshot 2024-11-27 135200](https://github.com/user-attachments/assets/fbbca245-a932-4fac-a1e9-f0acfb5621bd)

Here is the terminal output showing the error:

```
PS E:\Neutralinojs> neu create tyo  
neu: INFO Checking if neutralinojs/neutralinojs-minimal is a valid Neutralinojs app template...  
neu: INFO Downloading neutralinojs/neutralinojs-minimal template to tyo directory...  
neu: INFO Extracting template zip file...  
neu: INFO Downloading Neutralinojs binaries..  
neu: INFO Found the latest release tag v5.4.0 for neutralinojs...  
node:events:497  
      throw er; // Unhandled 'error' event  
      ^  

Error: read ECONNRESET  
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:218:20)  
Emitted 'error' event on Writable instance at:  
    at eventHandlers.<computed> (C:\Users\HP\AppData\Roaming\npm\node_modules\@neutralinojs\neu\node_modules\follow-redirects\index.js:49:24)  
    at ClientRequest.emit (node:events:519:28)  
    at TLSSocket.socketErrorListener (node:_http_client:500:9)  
    at TLSSocket.emit (node:events:519:28)  
    at emitErrorNT (node:internal/streams/destroy:169:8)  
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)  
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {  
  errno: -4077,  
  code: 'ECONNRESET',  
  syscall: 'read'  
}  

Node.js v20.16.0  
```
Specifications

- OS: Windows 11 x64
- Neutralinojs version: v5.4.0
- Neutralinojs client library version: Not applicable (unable to create app).
- Neutralinojs CLI version: v11.3.0
- Node.js version: v20.16.0

**Additional context**
This issue seems related to the network connection while downloading the Neutralinojs binaries. I’ve ensured my internet connection is stable and retried the command multiple times, but the issue persists. It may be related to how the CLI handles TLS/HTTP requests during the download process.

**Comment by ukhack** [comment]
the same.I don't know why desgin like that
```
PS D:\work> npm install -g @neutralinojs/neu
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated yaeti@0.0.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

added 99 packages in 9s

12 packages are looking for funding
  run `npm fund` for details
PS D:\work> neu create myapp2
neu: INFO Checking if neutralinojs/neutralinojs-minimal is a valid Neutralinojs app template...
neu: INFO Downloading neutralinojs/neutralinojs-minimal template to myapp2 directory...
node:events:498
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 20.205.243.166:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
Emitted 'error' event on Writable instance at:
    at eventHandlers.<computed> (C:\Users\80223576\AppData\Local\Volta\tools\image\packages\@neutralinojs\neu\node_modules\@neutralinojs\neu\node_modules\follow-redirects\index.js:49:24)
    at ClientRequest.emit (node:events:520:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '20.205.243.166',
  port: 443
}
```
