### ISSUE TITLE
Trying to replicate browser based terminal example, but seeing no such file or directory, stat 'clickmeapp-mac'

### ISSUE THREAD

**Issue by tomachinz** [neutralinojs/neutralinojs#411]
Likely a simple question getting dev env up. 
Neutrallinojs looks awesome - but I've found all of the docs and both tutorials to be a bit spares on the basic setup. 
- do I need to run `npm i` in here or parent? neither have a package file though
- when I `neu build` is also complains about the missing package.json file - am I expected to create one?
- when I `neu run` I get Error: ENOENT: no such file or directory, stat 'clickmeapp-mac'
- I using nvm on macOS 10.14 and node v12 
- does Neutralino compile my app? it looks like maybe not and it has 3 stub loaders for each OS and some webpacked interpreted js source goes with the app yeah?

```
➜  neutralinojs-browser-terminal git:(master) ✗ pwd
/Users/tom/Github/neutralinojs-desktop-samples/neutralinojs-browser-terminal
➜  neutralinojs-browser-terminal git:(master) ✗ neu build
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/tom/Github/neutralinojs-desktop-samples/neutralinojs-browser-terminal/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/tom/Github/neutralinojs-desktop-samples/neutralinojs-browser-terminal/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tom/.npm/_logs/2020-09-10T01_17_38_274Z-debug.log

➜  neutralinojs-browser-terminal git:(master) ✗ neu run
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, stat 'clickmeapp-mac'
    at Object.statSync (fs.js:933:3)
    at module.exports (/Users/tom/.nvm/versions/node/v12.16.3/lib/node_modules/@neutralinojs/neu/node_modules/chmod/index.js:12:26)
    at Object.module.exports.runApp (/Users/tom/.nvm/versions/node/v12.16.3/lib/node_modules/@neutralinojs/neu/src/modules/runner.js:16:13)
    at Command.<anonymous> (/Users/tom/.nvm/versions/node/v12.16.3/lib/node_modules/@neutralinojs/neu/src/commands/run.js:10:20)
    at Command.listener (/Users/tom/.nvm/versions/node/v12.16.3/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:370:29)
    at Command.emit (events.js:310:20)
    at Command.parseArgs (/Users/tom/.nvm/versions/node/v12.16.3/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:892:12)
    at Command.parse (/Users/tom/.nvm/versions/node/v12.16.3/lib/node_modules/@neutralinojs/neu/node_modules/commander/index.js:642:21)
    at Object.<anonymous> (/Users/tom/.nvm/versions/node/v12.16.3/lib/node_modules/@neutralinojs/neu/bin/neu.js:9:9)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'clickmeapp-mac'
}
➜  neutralinojs-browser-terminal git:(master) ✗ which neu
/Users/tom/.nvm/versions/node/v12.16.3/bin/neu
➜  neutralinojs-browser-terminal git:(master) ✗ which npm
/Users/tom/.nvm/versions/node/v12.16.3/bin/npm
```

**Comment by shalithasuranga** [comment]
Looks like you are trying very older versions of examples. Please check modern sample apps here: https://neutralino.js.org/apps/
