### ISSUE TITLE
"EACCES: permission denied" received when building release

### ISSUE THREAD

**Issue by richb-hanover** [neutralinojs/neutralinojs#481]
* I am starting out with neutralino to see if I like it. I have a fresh install of neutralino 2.3.0 (`yarn global add @neutralinojs/neu`) on macOS 10.15.7

* `neu create firstneuapp` worked as described in the "Getting Started". So did `cd firstneuapp && neu run`

* I then entered `neu build --release` and got this error:

```
Error: EACCES: permission denied, copyfile 'bin/neutralino-mac' -> 'dist/firstneuapp/firstneuapp-mac'
```

**Expected Behavior**  
I had expected to build the binaries without error

**Actual Behavior**  
The full output from the build step is below. Linux & Win10 binaries seem to be present (although I have not tested them). No macOS binary.

**Steps to Reproduce the Problem**  
 1. See description above

**Specifications**  
* NeutralinoJs Version: [Version number of NeutralinoJs framework] 2.3.0
* NeutralinoJs CLI version: [neu-cli version] 5.0.0
* Platform: [Platform specifications]  macOS 10.15.7

**Full error log**
```
?130 firstneuapp % neu build --release
Bundling app...
Generating res.neu...
Copying binaries...
Error: EACCES: permission denied, copyfile 'bin/neutralino-mac' -> 'dist/firstneuapp/firstneuapp-mac'
    at Object.copyFileSync (fs.js:1941:3)
    at copyFile (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:67:6)
    at onFile (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:53:25)
    at getStats (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
    at startCopy (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at Object.module.exports.bundleApp (/Users/richb/.config/yarn/global/node_modules/@neutralinojs/neu/src/modules/bundler.js:34:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.<anonymous> (/Users/richb/.config/yarn/global/node_modules/@neutralinojs/neu/src/commands/build.js:11:13) {
  errno: -13,
  syscall: 'copyfile',
  code: 'EACCES',
  path: 'bin/neutralino-mac',
  dest: 'dist/firstneuapp/firstneuapp-mac'
}
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
Please check the ./dist directory!

√ firstneuapp % ll dist
total 0
drwxr-xr-x   3 richb  staff    96B Jun 19 07:33 .
drwxr-xr-x  11 richb  staff   352B Jun 19 07:33 ..
drwxr-xr-x   5 richb  staff   160B Jun 19 07:33 firstneuapp

√ firstneuapp % ll dist/firstneuapp
total 9736
drwxr-xr-x  5 richb  staff   160B Jun 19 07:33 .
drwxr-xr-x  3 richb  staff    96B Jun 19 07:33 ..
-rw-r--r--  1 richb  staff   3.2M Jun 19 07:33 firstneuapp-linux
-rw-r--r--  1 richb  staff   1.5M Jun 19 07:33 firstneuapp-win.exe
-rw-r--r--  1 richb  staff    28K Jun 19 07:33 res.neu

?1 firstneuapp % neu version
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
--- Global ---
Neutralinojs binaries: v2.3.0
neu CLI: v5.0.0

--- Project: firstneuapp (js.neutralino.sample) ---
Neutralinojs binaries: v2.3.0
√ firstneuapp %
```

**Comment by julienhyg** [comment]
Hi Rich!

I had the exact same issue (binaries 2.4.0 and CLI 5.1.2 on macOS 11.4).

I simply ran `chmod 664 bin/neutralino-mac`. Then using `new build --release` works!

Hope this helps, let me know.

**Comment by richb-hanover** [comment]
@julienhyg Yes! I used `chmod 644 bin/neutralino-mac` and then `neu build --release` and it built without error. (Also, I reloaded neutralino to use version 2.4.0 (that's several hours old...))

@shalithasuranga - this would be important to fix this error. It scares away newcomers to Neutralino if the initial project cannot be built without errors. Thanks!

**Comment by richb-hanover** [comment]
One last comment: to make the built app actually work on macOS, I had to do this:

```
$ chmod +x dist/firstneuapp/firstneuapp-mac
$ dist/firstneuapp/firstneuapp-mac
```
Could this be made part of the build command? Thanks.
