### ISSUE TITLE
Getting Started: Can't 'run' or 'build' starter app on macOS

### ISSUE THREAD

**Issue by richb-hanover** [neutralinojs/neutralinojs#528]
Using neutralinojs 2.4.0 / 5.1.3 on macOS 10.15.7, I followed the [First Neutralino App](https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app) steps:

```
yarn global add @neutralinojs/neu
neu create firstneuapp
cd firstneuapp
neu run
neu build --release
```
@shalithasuranga I am sorry to report that I received several error messages with the 5.1.3 build:

1. `neu run` flashed up the GUI very briefly, and gave a message *Application was terminated.*
2. `neu build --release` gave *Error: EACCES: permission denied, copyfile 'bin/neutralino-mac' -> 'dist/firstneuapp/firstneuapp-mac'* (This looks similar to neutralinojs/neutralinojs-cli#54 .)
3. Applying `chmod 764 bin/neutralino-mac` as suggested in a comment permits the build step to work, but...
4. Running `./dist/firstneuapp/firstneuapp-mac` gives *zsh: segmentation fault  ./dist/firstneuapp/firstneuapp-mac*

Here is the full output

```
√ github % yarn global add @neutralinojs/neu
yarn global v1.22.10
warning package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "@neutralinojs/neu@5.1.3" with binaries:
      - neu
✨  Done in 3.02s.
√ github % neu version
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
--- Global ---
Neutralinojs binaries: v2.4.0
Neutralinojs client: v1.0.0
neu CLI: v5.1.3
INFO Run this command inside your project directory to get project specific Neutralinojs version.
√ github % neu create firstneuapp
Downloading minimal template to firstneuapp directory...
Extracting template zip file..
Downloading Neutralinojs binaries..
Extracting zip file..
Finalizing and cleaning temp. files.
Downloading the Neutralinojs client..
Finalizing and cleaning temp. files.

----
Enter 'cd firstneuapp && neu run' to run your application.
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
√ github % cd firstneuapp
√ firstneuapp % neu run
Application was terminated.
√ firstneuapp % neu build --release
Bundling app...
Generating res.neu...
Copying binaries...
Error: EACCES: permission denied, copyfile 'bin/neutralino-mac' -> 'dist/firstneuapp/firstneuapp-mac'
    at Object.copyFileSync (fs.js:1941:3)
    at copyFile (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:67:6)
    at onFile (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:53:25)
    at getStats (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
    at startCopy (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at Object.module.exports.bundleApp (/Users/richb/.config/yarn/global/node_modules/@neutralinojs/neu/src/modules/bundler.js:34:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.<anonymous> (/Users/richb/.config/yarn/global/node_modules/@neutralinojs/neu/src/commands/build.js:11:13) {
  errno: -13,
  syscall: 'copyfile',
  code: 'EACCES',
  path: 'bin/neutralino-mac',
  dest: 'dist/firstneuapp/firstneuapp-mac'
}
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
Please check the ./dist directory!
√ firstneuapp % ll
total 32
drwxr-xr-x   11 richb  staff   352B Jul  4 07:34 .
drwxr-xr-x  308 richb  staff   9.6K Jul  4 07:34 ..
-rw-r--r--    1 richb  staff   185B Jul  4 07:34 .gitignore
-rw-r--r--    1 richb  staff   1.1K Jul  4 07:34 LICENSE
-rw-r--r--    1 richb  staff   515B Jul  4 07:34 README.md
drwxr-xr-x    6 richb  staff   192B Jul  4 07:34 bin
drwxr-xr-x    3 richb  staff    96B Jul  4 07:34 dist
-rw-r--r--    1 richb  staff   815B Jul  4 07:34 neutralino.config.json
-rw-r--r--    1 richb  staff     0B Jul  4 07:34 neutralinojs.log
drwxr-xr-x    6 richb  staff   192B Jul  4 07:34 resources
drwxr-xr-x    4 richb  staff   128B Jul  4 07:34 temp
√ firstneuapp % ll dist
total 0
drwxr-xr-x   3 richb  staff    96B Jul  4 07:34 .
drwxr-xr-x  11 richb  staff   352B Jul  4 07:34 ..
drwxr-xr-x   5 richb  staff   160B Jul  4 07:34 firstneuapp
√ firstneuapp % ll dist/firstneuapp
total 4664
drwxr-xr-x  5 richb  staff   160B Jul  4 07:34 .
drwxr-xr-x  3 richb  staff    96B Jul  4 07:34 ..
-rw-r--r--  1 richb  staff   753K Jul  4 07:34 firstneuapp-linux
-rw-r--r--  1 richb  staff   1.5M Jul  4 07:34 firstneuapp-win.exe
-rw-r--r--  1 richb  staff    32K Jul  4 07:34 res.neu
√ firstneuapp % ll bin
total 7384
drwxr-xr-x   6 richb  staff   192B Jul  4 07:34 .
drwxr-xr-x  11 richb  staff   352B Jul  4 07:34 ..
-rw-r--r--   1 richb  staff   418K Jul  4 07:34 WebView2Loader.dll
-rw-r--r--   1 richb  staff   753K Jul  4 07:34 neutralino-linux
--wxrw--wt   1 richb  staff   970K Jul  4 07:34 neutralino-mac
-rw-r--r--   1 richb  staff   1.5M Jul  4 07:34 neutralino-win.exe
```

**Comment by richb-hanover** [comment]
Thanks. Please let me know what other information I could collect to debug this.

**Comment by markaljhon** [comment]
Same issue with Windows 10

Neutralinojs binaries: v2.5.0
Neutralinojs client: v1.2.0
neu CLI: v5.3.1

**Comment by richb-hanover** [comment]
@shalithasuranga **Update:** Using the same process as the original post, I still have errors trying to `run` or `build` **on macOS** with Neutralinojs v2.6.0; Neutralinojs client: v1.3.0; neu CLI: v6.0.3.  As always, please let me know what information I could provide to help debug this. Thanks.

```
√ ~ % yarn global add @neutralinojs/neu
yarn global v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "@neutralinojs/neu@6.0.3" with binaries:
      - neu
✨  Done in 3.88s.
√ ~ % cd github
√ github % rm -rf firstneuapp
√ github % neu create firstneuapp
Downloading minimal template to firstneuapp directory...
Extracting template zip file..
Downloading Neutralinojs binaries..
Extracting zip file..
Finalizing and cleaning temp. files.
Downloading the Neutralinojs client..
Finalizing and cleaning temp. files.

----
Enter 'cd firstneuapp && neu run' to run your application.
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
√ github % cd firstneuapp
√ firstneuapp % neu run
Starting process: neutralino-mac_x64  --load-dir-res --path=. --debug-mode
devAPIServer listening at http://localhost:5050
neutralino-mac_x64 was stopped.
√ firstneuapp % neu version
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
--- Global ---
Neutralinojs binaries: v2.6.0
Neutralinojs client: v1.3.0
neu CLI: v6.0.3

--- Project: firstneuapp (js.neutralino.sample) ---
Neutralinojs binaries: v2.6.0
Neutralinojs client: v1.3.0
√ firstneuapp % neu build --release
Bundling app...
Generating res.neu...
Copying binaries...
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
Please check the ./dist directory!
√ firstneuapp % ./dist/firstneuapp/firstneuapp-mac
zsh: no such file or directory: ./dist/firstneuapp/firstneuapp-mac
?127 firstneuapp % ./bin/neutralino-mac --path=.
zsh: no such file or directory: ./bin/neutralino-mac
?127 firstneuapp % ll .dist
zsh: correct '.dist' to 'dist' [nyae]? n
ls: .dist: No such file or directory
?1 firstneuapp % ll
total 32
drwxr-xr-x   10 richb  staff   320B Aug 10 14:23 .
drwxr-xr-x  304 richb  staff   9.5K Aug 10 14:22 ..
-rw-r--r--    1 richb  staff   185B Aug 10 14:22 .gitignore
-rw-r--r--    1 richb  staff   1.1K Aug 10 14:22 LICENSE
-rw-r--r--    1 richb  staff   515B Aug 10 14:22 README.md
drwxr-xr-x    7 richb  staff   224B Aug 10 14:22 bin
drwxr-xr-x    4 richb  staff   128B Aug 10 14:23 dist
-rw-r--r--    1 richb  staff   815B Aug 10 14:22 neutralino.config.json
-rw-r--r--    1 richb  staff     0B Aug 10 14:22 neutralinojs.log
drwxr-xr-x    6 richb  staff   192B Aug 10 14:22 resources
√ firstneuapp % ll dist
total 3088
drwxr-xr-x   4 richb  staff   128B Aug 10 14:23 .
drwxr-xr-x  10 richb  staff   320B Aug 10 14:23 ..
drwxr-xr-x   8 richb  staff   256B Aug 10 14:23 firstneuapp
-rw-r--r--   1 richb  staff   1.5M Aug 10 14:23 firstneuapp-release.zip
√ firstneuapp % ll dist/firstneuapp
total 9072
drwxr-xr-x  8 richb  staff   256B Aug 10 14:23 .
drwxr-xr-x  4 richb  staff   128B Aug 10 14:23 ..
-rw-r--r--  1 richb  staff   418K Aug 10 14:23 WebView2Loader.dll
-rw-r--r--  1 richb  staff   806K Aug 10 14:23 firstneuapp-linux_ia32
-rw-r--r--  1 richb  staff   772K Aug 10 14:23 firstneuapp-linux_x64
-rwxr-xr-x  1 richb  staff   991K Aug 10 14:23 firstneuapp-mac_x64
-rw-r--r--  1 richb  staff   1.5M Aug 10 14:23 firstneuapp-win_x64.exe
-rw-r--r--  1 richb  staff    31K Aug 10 14:23 res.neu
√ firstneuapp % ./dist/firstneuapp/firstneuapp-mac_x64
zsh: segmentation fault  ./dist/firstneuapp/firstneuapp-mac_x64
?139 firstneuapp %
```

**Comment by richb-hanover** [comment]
@shalithasuranga - I get substantially the same segfault on macOS 10.15.7 using the updated Neutralinojs:

Neutralinojs binaries: v2.7.0
Neutralinojs client: v1.4.0
neu CLI: v6.1.0

```
√ github % yarn global add @neutralinojs/neu
yarn global v1.22.11
warning package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "@neutralinojs/neu@6.1.0" with binaries:
      - neu
✨  Done in 9.03s.
√ github % neu create firstneuapp
Downloading minimal template to firstneuapp directory...
Extracting template zip file..
Downloading Neutralinojs binaries..
Extracting zip file..
Finalizing and cleaning temp. files.
Downloading the Neutralinojs client..
Finalizing and cleaning temp. files.

----
Enter 'cd firstneuapp && neu run' to run your application.
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
√ github % cd firstneuapp
√ firstneuapp % neu version
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
--- Global ---
Neutralinojs binaries: v2.7.0
Neutralinojs client: v1.4.0
neu CLI: v6.1.0

--- Project: firstneuapp (js.neutralino.sample) ---
Neutralinojs binaries: v2.7.0
Neutralinojs client: v1.4.0
√ firstneuapp % neu run
Starting process: neutralino-mac_x64  --load-dir-res --path=. --debug-mode
devAPIServer listening at http://localhost:5050
neutralino-mac_x64 was stopped with error code null
√ firstneuapp % neu build --release
Bundling app...
Generating res.neu...
Copying binaries...
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
Please check the ./dist directory!
√ firstneuapp % ./dist/firstneuapp/firstneuapp-mac_x64
zsh: segmentation fault  ./dist/firstneuapp/firstneuapp-mac_x64
```

**Comment by richb-hanover** [comment]
@shalithasuranga - I see that three people have responded with a confused emoji. Am I the only one who is seeing this? (I see the same thing with neu CLI 6.1.1, too)

What other information could I supply to help troubleshoot this?

**Comment by richb-hanover** [comment]
This isn't getting worked on, even with 2.8.0. I'm going to close this and resubmit a new report with fresh info. Thanks.

**Comment by shalithasuranga** [comment]
Hey.. @richb-hanover Thanks for checking again with the new version. Yeah nice that you created a new issue. I will reply an approach to find the issue behind this there..
