### ISSUE TITLE
os.setTray crashing app on macOS Catalina 10.15.7

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#615]
Ref: https://github.com/neutralinojs/neutralinojs/issues/614

**Comment by alectrocute** [comment]
Also affecting macOS 12.1, FWIW.

**Comment by welljsjs** [comment]
Not trying to be too impatient but is there any update on this as to what is the underlying issue?
Is there any workaround available?
Just causing us a little headache atm.

**Comment by Blatman** [comment]
Not sure if it will help but the os.setTray works for me on M1 Mac running Monterey 12.1 (Safari 15) (Rosetta2 installed).

Is there something in the setTray code causing the crash or is it a Catalina thing?

eg:
Using this code works OK -

Neutralino.init();
... whatever ...
if ((NL_OS == "Darwin") && ((NL_MODE == "window") || (NL_MODE == "chrome"))) {
    window.myApp.setTray();
    window.myApp.setWindowDraggable();
}


    setTray: () => {
        if ((NL_MODE != "window") && (NL_MODE != "chrome")) {
            console.log("INFO: Tray menu is only available in the window or chrome mode.");
            return;
        }

        let tray = {
            icon: "/icons/trayIcon.png",
            menuItems: [
                {
                    id: "VERSION",
                    text: "Get version"
                },
                {
                    id: "SEP",
                    text: "-"
                },
                {
                    id: "CHECKO",
                    text: "Example: checked",
                    isChecked: true
                },
                {
                    id: "QUESTION",
                    text: "Example: question"
                },
                {
                    id: "DISABLED",
                    text: "Example: disabled",
                    isDisabled: true
                },
                {
                    id: "NOTIFY",
                    text: "Example: notification"
                },
                {
                    id: "APID",
                    text: "Example: App PID"
                },
                {
                    id: "SEP2",
                    text: "-"
                },
                {
                    id: "QUIT",
                    text: "Quit"
                }
            ]
        };
        console.log(Date.now() + ' - try setTray');
        var trayo = Neutralino.os.setTray(tray)
            .then(function (trayo) {
                console.log(Date.now() + ' - BINGO, setTray worked ', trayo);
            })
            .catch(function (err) {
                console.log(Date.now() + 'errSetTray', err);
            })
    },

**Comment by welljsjs** [comment]
This is the relevant call stack: 

```
--- STDERR ---
2022-02-03 11:06:31.095 neutralino-mac_x64[11816:165460] NSWindow warning: adding an unknown subview: <WKInspectorWKWebView: 0x7fa8e4f0c430>. Break on NSLog to debug.
2022-02-03 11:06:31.097 neutralino-mac_x64[11816:165460] Call stack:
(
        0   AppKit                              0x00007ff81a1a5dc6 -[NSThemeFrame addSubview:] + 112
        1   AppKit                              0x00007ff81a1a5b06 -[NSView addSubview:positioned:relativeTo:] + 203
        2   AppKit                              0x00007ff81a1a59be -[NSThemeFrame addSubview:positioned:relativeTo:] + 46
        3   WebKit                              0x00007ff91b7d00a5 _ZN6WebKit19WebInspectorUIProxy14platformAttachEv + 391
        4   WebKit                              0x00007ff91b8ea262 _ZN6WebKit19WebInspectorUIProxy4openEv + 84
        5   WebKit                              0x00007ff91bb126e6 _ZN6WebKit19WebInspectorUIProxy17didReceiveMessageERN3IPC10ConnectionERNS1_7DecoderE + 242
        6   WebKit                              0x00007ff91b47f21d _ZN3IPC18MessageReceiverMap15dispatchMessageERNS_10ConnectionERNS_7DecoderE + 199
        7   WebKit                              0x00007ff91b87afcb _ZN6WebKit15WebProcessProxy17didReceiveMessageERN3IPC10ConnectionERNS1_7DecoderE + 31
        8   WebKit                              0x00007ff91b45c9be _ZN3IPC10Connection15dispatchMessageENSt3__110unique_ptrINS_7DecoderENS1_14default_deleteIS3_EEEE + 634
        9   WebKit                              0x00007ff91b45c190 _ZN3IPC10Connection24dispatchIncomingMessagesEv + 408
        10  JavaScriptCore                      0x00007ff830d2ed4f _ZN3WTF7RunLoop11performWorkEv + 287
        11  JavaScriptCore                      0x00007ff830d2fcaa _ZN3WTF7RunLoop11performWorkEPv + 26
        12  CoreFoundation                      0x00007ff8177518fd __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
        13  CoreFoundation                      0x00007ff817751865 __CFRunLoopDoSource0 + 180
        14  CoreFoundation                      0x00007ff8177515e4 __CFRunLoopDoSources0 + 242
        15  CoreFoundation                      0x00007ff81775001b __CFRunLoopRun + 893
        16  CoreFoundation                      0x00007ff81774f5dd CFRunLoopRunSpecific + 563
        17  HIToolbox                           0x00007ff82038c4f1 RunCurrentEventLoopInMode + 292
        18  HIToolbox                           0x00007ff82038c247 ReceiveNextEventCommon + 587
        19  HIToolbox                           0x00007ff82038bfe5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
        20  AppKit                              0x00007ff81a17ed88 _DPSNextEvent + 886
        21  AppKit                              0x00007ff81a17d3f4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1411
        22  AppKit                              0x00007ff81a16f919 -[NSApplication run] + 586
        23  neutralino-mac_x64                  0x000000010cd4cdb1 _ZN7webview22cocoa_wkwebview_engine3runEv + 165
        24  neutralino-mac_x64                  0x000000010cd4e416 _ZN6window11controllers14__createWindowEv + 567
        25  neutralino-mac_x64                  0x000000010cd4fd8f _ZN6window11controllers4initERKN8nlohmann10basic_jsonINSt3__13mapENS3_6vectorENS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEbxydS9_NS1_14adl_serializerENS5_IhNS9_IhEEEEEE + 1069
        26  neutralino-mac_x64                  0x000000010cd00e6a _Z10__startAppv + 635
        27  neutralino-mac_x64                  0x000000010cd01900 main + 172
        28  dyld                                0x00000001139d44fe start + 462
)

--- STDOUT ---
```

**Comment by Blatman** [comment]
Looks like an Intel only issue then although Rosetta2 should react the same ....

**Comment by Blatman** [comment]
Was kind of curious as to where the above call stack was coming from and I get it whenever I open the Inspect Element dev console after the app has launched (double-clicking executable) - this occurs even if the previous code (setTray or extn code) has worked successfully or not. I will get these logs in this scenario on 12.2 Monterey back to 10.13 High Sierra. If the executable is packaged as a normal mac app (exec is in MacOS folder/ app files in Resources folder) and launched normally there is no problem.

**Comment by welljsjs** [comment]
Yeah sorry about that I think the above call stack is indeed unrelated to the actual issue with setTray

> ... and launched normally there is no problem.

Now you're referring to setTray or the warning from above?

**Comment by Blatman** [comment]
Yea - the warning above only occurs when the dev tools are opened (WKInspectorWKWebView) when using the executable directly in terminal mode.
The setTray works for me OK but the original code for this issue failure is not available so don't know the story there and I don't have Catalina to try it on. Must be a curly one since it has gone to GSOC!

**Comment by richb-hanover** [comment]
This still seems to be a problem (macOS 10.15.7, Intel MacBook Pro). I get `neutralino-mac_x64 was stopped with error code null` when calling setTray() (The call to setTray() is still commented out in the starter app.)

I just tested with Neutralino Server 4.4.0, Client 3.3.0 (build from a couple days ago). Using the [standard procedure](https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app) for creating the starter app, `neu run` looks and works OK: It opens the expected window (below), if I bring another app to the front, clicking the tray/dock icon brings the starter app back to the front, clicking the red dot (upper left) quits the application with "success code 0" as expected.

```
# THIS WORKS
√ firstneuapp % neu run
Starting process: neutralino-mac_x64  --load-dir-res --path=. --debug-mode
devAPIServer listening at http://localhost:5050
neutralino-mac_x64 was stopped with success code 0
```

![image](https://user-images.githubusercontent.com/1094930/158060594-a5ae2a4a-0b5c-4a91-8d96-fbd1365a9f49.png)

**BUT...** Changing the starter app code to call setTray() (comment out the `if` statements on lines 59 & 61 of _main.js_) I see the `error code null` message (below)

```
# THIS FAILS WHEN setTray() IS CALLED
√ firstneuapp % neu run
Starting process: neutralino-mac_x64  --load-dir-res --path=. --debug-mode
devAPIServer listening at http://localhost:5050
neutralino-mac_x64 was stopped with error code null
```

**Comment by richb-hanover** [comment]
Update: `neu build --release` from the same directory as the prior report gives the following crash:

```
√ firstneuapp % neu build --release
Bundling app...
Generating res.neu...
Copying binaries...
Error: ENOENT: no such file or directory, stat 'bin/neutralino-linux_ia32'
    at Object.statSync (fs.js:1042:3)
    at Object.statSync (/Users/richb/.config/yarn/global/node_modules/graceful-fs/polyfills.js:311:34)
    at statSync (/Users/richb/.config/yarn/global/node_modules/@neutralinojs/neu/node_modules/fs-extra/lib/util/stat.js:10:52)
    at getStatsSync (/Users/richb/.config/yarn/global/node_modules/@neutralinojs/neu/node_modules/fs-extra/lib/util/stat.js:24:19)
    at Object.checkPathsSync (/Users/richb/.config/yarn/global/node_modules/@neutralinojs/neu/node_modules/fs-extra/lib/util/stat.js:49:33)
    at Object.copySync (/Users/richb/.config/yarn/global/node_modules/@neutralinojs/neu/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
    at Object.module.exports.bundleApp (/Users/richb/.config/yarn/global/node_modules/@neutralinojs/neu/src/modules/bundler.js:38:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.<anonymous> (/Users/richb/.config/yarn/global/node_modules/@neutralinojs/neu/src/commands/build.js:11:13) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'bin/neutralino-linux_ia32'
}
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
Please check the ./dist directory!
√ firstneuapp %
```

**Comment by richb-hanover** [comment]
@shalithasuranga Why would a macOS build try to include _bin/neutralino-linux_ia32?_  (see above) Thanks.

**Comment by Blatman** [comment]
Just for curiosity does anyone have an example of code within the setTray() function that fails or does it only fail when using the CLI? eg: I do know that if say the icon path option is unavailable or misspelt then the app will crash with a segmentation trap.

**Comment by DEVLOPRR** [comment]
Segmentation fault means it's a problem inside the Neutralino C++ Code itself and not the client file

**Comment by Blatman** [comment]
Yes that may be the case. As far as I can see for me the setTray works OK in a normal mac app scenario provided the icon path etc is OK but it appears that the issue may be occurring if the CLI is being used. I have noticed that even with the CLI if the icon path is not right then a crash will occur.

**Comment by wobsoriano** [comment]
If it helps, this currently works on Monterey 12.3

**Comment by denisw** [comment]
If the issue is a segfault, then you could perhaps try if #1010 fixes the issue. It adapts to changes to the `objc_msgSend` function signature by explicitly casting all uses of `objc_msgSend` to the matching function type, which ensures that the parameters are passed exactly as expected.

**Comment by brandon-kyle-bailey** [comment]
Any updated on this? Been open for a while by the looks of it

**Comment by richcouzzi** [comment]
On a M1 MPB with Monterey v 12.6 - I uncommented the conditional check `if(NL_OS != "Darwin")` in the `main.js` file created by `neu create`. I am able to confirm the `setTray()` call does work, and without crashes or error.

**Comment by Aeiddius** [comment]
any news?

**Comment by OrigamingWasTaken** [comment]
Re-asking if any workaround was found?

**Comment by Bootta11** [comment]
Look like its working on current OS version(Sequoia). Can someone recheck.

**Comment by bitsnaps** [comment]
Same issue for macOS 11.7.10, here is the log:
```
dyld: Library not loaded: /System/Library/Frameworks/ScreenCaptureKit.framework/Versions/A/ScreenCaptureKit
  Referenced from: /path/to/project/hello/helloapp/bin/neutralino-mac_x64
  Reason: image not found

```
