### ISSUE TITLE
v4.0.0 - Missing linux_ia32 binary

### ISSUE THREAD

**Issue by MacFJA** [neutralinojs/neutralinojs#727]
Due to a missing binary, installation of Neutralino is impossible

**Expected Behavior**  
I'm unable to run `npx @neutralinojs/neu update`, the script fail with this message:
```
(node:18708) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat 'temp/neutralino-linux_ia32'
    at Object.statSync (fs.js:1086:3)
    at Object.statSync (/xxx/.npm/_npx/0214858268217ccb/node_modules/graceful-fs/polyfills.js:311:34)
    at statSync (/xxx/.npm/_npx/0214858268217ccb/node_modules/fs-extra/lib/util/stat.js:10:52)
    at getStatsSync (/xxx/.npm/_npx/0214858268217ccb/node_modules/fs-extra/lib/util/stat.js:24:19)
    at Object.checkPathsSync (/xxx/.npm/_npx/0214858268217ccb/node_modules/fs-extra/lib/util/stat.js:49:33)
    at Object.copySync (/xxx/.npm/_npx/0214858268217ccb/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
    at Object.module.exports.downloadAndUpdateBinaries (/xxx/.npm/_npx/0214858268217ccb/node_modules/@neutralinojs/neu/src/modules/downloader.js:90:17)
    at async Command.<anonymous> (/xxx/.npm/_npx/0214858268217ccb/node_modules/@neutralinojs/neu/src/commands/update.js:9:13)
```

And I can see that the binary is present [in 3.0.0](https://github.com/neutralinojs/neutralinojs/tree/v3.0.0/bin), not [in 4.0.0](https://github.com/neutralinojs/neutralinojs/tree/v4.0.0/bin)
  
**Actual Behavior**  
The command `npx @neutralinojs/neu update` is executed without any issue

**Steps to Reproduce the Problem**  
 1. Just run `npx @neutralinojs/neu create myapp`

**Specifications**  
* NeutralinoJs Version: 4.0.0
* NeutralinoJs CLI version: 3.0.0
* Platform: macOS 10.15

**Comment by shalithasuranga** [comment]
Hey thanks for checking v4. Could you try to use `@latest` at the end of the npx package. The previous cli isn't compatible with v4

**Comment by MacFJA** [comment]
Oh, that works!
And after purging my `npx` cache it also work without adding the `@latest`.

Sorry for the false alert !
